export const ml = {
  navigation: {
    home: "ഹോം",
    sale: "വിൽപ്പന",
    dashboard: "ഡാഷ്ബോർഡ്",
    offers: "ഓഫറുകൾ",
    history: "ചരിത്രം",
    more: "കൂടുതൽ",
    settings: "ക്രമീകരണങ്ങൾ",
  },
  stock: {
    picked: "എടുത്തത്",
    sold: "വിറ്റത്",
    remaining: "ബാക്കി",
    stock: "സ്റ്റോക്ക്",
    lowStock: "സ്റ്റോക്ക് കുറവ്",
    shortage: "കുറവ്",
    missingQuantity: "കുറവുള്ള എണ്ണം",
    unitsSold: "വിറ്റ എണ്ണം",
    totalSold: "ആകെ വിറ്റത്",
    totalUnitsSold: "ആകെ വിറ്റ എണ്ണം",
    totalPicked: "ആകെ എടുത്തത്",
    previouslyPicked: "മുമ്പ് എടുത്തത്",
    left: "ബാക്കി",
  },
  actions: {
    startNewDay: "പുതിയ ദിവസം ആരംഭിക്കുക",
    dayStart: "ദിവസം ആരംഭിക്കൽ",
    dayClose: "ദിവസം അവസാനിപ്പിക്കുക",
    reopenCurrentDay: "ഇന്നത്തെ ദിവസം വീണ്ടും തുറക്കുക",
    additionalPickup: "കൂടുതൽ ഉൽപ്പന്നങ്ങൾ എടുക്കുക",
    resetActiveBusinessDay: "നിലവിലെ ബിസിനസ് ദിവസം റീസെറ്റ് ചെയ്യുക",
    save: "സേവ് ചെയ്യുക",
    confirm: "സ്ഥിരീകരിക്കുക",
    cancel: "റദ്ദാക്കുക",
    continue: "തുടരുക",
    back: "തിരികെ",
    close: "അടയ്ക്കുക",
    edit: "തിരുത്തുക",
    delete: "ഇല്ലാതാക്കുക",
    review: "പരിശോധിക്കുക",
    retry: "വീണ്ടും ശ്രമിക്കുക",
    saveExpenses: "ചെലവുകൾ സേവ് ചെയ്യുക",
    applyFilter: "ഫിൽറ്റർ പ്രയോഗിക്കുക",
    clearFilter: "ഫിൽറ്റർ നീക്കുക",
    markAsReceived: "സ്വീകരിച്ചതായി രേഖപ്പെടുത്തുക",
    undo: "പഴയ നിലയിലാക്കുക",
    resetToEarned: "ലഭിച്ച നിലയിലേക്ക് മാറ്റുക",
    viewPreviousDay: "മുൻപത്തെ ദിവസം കാണുക",
    closePreviousDay: "മുൻപത്തെ ദിവസം അടയ്ക്കുക",
    add: "ചേർക്കുക",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക",
    openNewDay: "പുതിയ ദിവസം തുറക്കുക",
    viewDaySummary: "ദിവസത്തെ സംഗ്രഹം കാണുക",
    openWhatsappReport: "വാട്ട്സ്ആപ്പ് റിപ്പോർട്ട് തുറക്കുക",
    reopenCurrentDayCaps: "ഇന്നത്തെ ദിവസം വീണ്ടും തുറക്കുക",
    resetCurrentDayCaps: "ഇന്നത്തെ ദിവസം റീസെറ്റ് ചെയ്യുക",
    confirmAdditionalPickupCaps: "കൂടുതലെടുത്തത് സ്ഥിരീകരിക്കുക",
    keepEditing: "തുടർന്നും എഡിറ്റ് ചെയ്യുക",
    discardDraft: "ഡ്രാഫ്റ്റ് വേണ്ടെന്നുവെക്കുക",
    selectPastBusinessDate: "പഴയ ബിസിനസ് തീയതി തിരഞ്ഞെടുക്കുക",
    cancelDraft: "ഡ്രാഫ്റ്റ് റദ്ദാക്കുക",
    returnSale: "വിൽപ്പന തിരികെ എടുക്കുക",
  },
  status: {
    businessDayClosed: "ബിസിനസ് ദിവസം അവസാനിപ്പിച്ചു",
    businessDay: "ബിസിനസ് ദിവസം",
    notStarted: "ആരംഭിച്ചിട്ടില്ല",
    open: "തുറന്നിരിക്കുന്നു",
    previousDayStillOpen: "കഴിഞ്ഞ ദിവസം ഇപ്പോഴും തുറന്നിരിക്കുന്നു",
    closed: "അടച്ചിരിക്കുന്നു",
    notPrepared: "തയ്യാറാക്കിയിട്ടില്ല",
    closedCaps: "അടച്ചു",
  },
  finance: {
    grossSales: "മൊത്തം വിൽപ്പന",
    normalCommission: "സാധാരണ കമ്മീഷൻ",
    offerEarnings: "ഓഫർ വരുമാനം",
    totalEarnings: "ആകെ വരുമാനം",
    netCollection: "ശേഖരണ തുക",
    amountPayableToCompany: "കമ്പനിക്ക് നൽകേണ്ട തുക",
    amountPayable: "നൽകേണ്ട തുക",
    totalExpenses: "ആകെ ചെലവ്",
    petrol: "പെട്രോൾ",
    food: "ഭക്ഷണം",
    otherExpense: "മറ്റ് ചെലവുകൾ",
    petrolExpense: "പെട്രോൾ ചെലവ്",
    foodExpense: "ഭക്ഷണ ചെലവ്",
    otherExpenses: "മറ്റ് ചെലവുകൾ",
    salespersonEarnings: "സെയിൽസ്മാൻ്റെ വരുമാനം",
    companyPayable: "കമ്പനിക്ക് നൽകേണ്ട തുക",
  },
  labels: {
    selected: "തിരഞ്ഞെടുത്തത്",
    inSale: "ഇപ്പോഴത്തെ വിൽപ്പന",
    quantity: "എണ്ണം",
    date: "തീയതി",
    time: "സമയം",
    today: "ഇന്ന്",
    yesterday: "ഇന്നലെ",
    thisMonth: "ഈ മാസം",
    previousMonth: "കഴിഞ്ഞ മാസം",
    specificDate: "പ്രത്യേക തീയതി",
    customRange: "തീയതി പരിധി",
    allTime: "മുഴുവൻ കാലയളവ്",
    last7: "കഴിഞ്ഞ 7 ദിവസം",
    specificMonth: "പ്രത്യേക മാസം",
    expenses: "ചെലവുകൾ",
    descriptionOptional: "വിവരണം (ഓപ്ഷണൽ)",
    amount: "തുക",
    totalOther: "ആകെ മറ്റ് ചെലവുകൾ",
    offersEarned: "ലഭിച്ച ഓഫറുകൾ",
    totalDailyExpenses: "പ്രതിദിന ആകെ ചെലവുകൾ",
    standardExpenses: "സാധാരണ ചെലവുകൾ",
    dailyExpenses: "പ്രതിദിന ചെലവുകൾ",
    productWiseStockReview: "ഉൽപ്പന്നം തിരിച്ചുളള സ്റ്റോക്ക് പരിശോധന",
    reviewStock: "എടുത്തതും വിറ്റതും ബാക്കിയുള്ളതുമായ മുഴുവൻ സ്റ്റോക്കും പരിശോധിക്കുക.",
    currentTime: "ഇപ്പോഴത്തെ സമയം",
    workingDuration: "പ്രവർത്തിച്ച സമയം",
    productsSelected: "തിരഞ്ഞെടുത്ത ഉൽപ്പന്നങ്ങൾ",
    totalPickedUnits: "ആകെ എടുത്ത എണ്ണം",
    totalAdditionalUnits: "കൂടുതലെടുത്ത ആകെ എണ്ണം",
    newTotalPicked: "പുതിയതായി ആകെ എടുത്തത്",
    newRemaining: "പുതിയ ബാക്കി",
    product: "ഉൽപ്പന്നം",
    offerValue: "ഓഫർ മൂല്യം",
    cycleNumber: "സൈക്കിൾ നമ്പർ",
    earnedDateTime: "ലഭിച്ച തീയതി/സമയം",
    salesHistory: "വിൽപ്പന ചരിത്രം",
    closedBusinessDays: "അടച്ച ബിസിനസ് ദിവസങ്ങൾ",
    businessDayClosureSummary: "ബിസിനസ് ദിവസം അവസാനിച്ചതിന്റെ സംഗ്രഹം",
    sessionSummary: "സെഷൻ സംഗ്രഹം",
    addEditExpenses: "ചെലവുകൾ ചേർക്കുക / തിരുത്തുക",
    edit: "(തിരുത്തുക)",
    salesmanName: "സെയിൽസ്മാന്റെ പേര്",
    businessName: "ബിസിനസ് പേര്",
    whatsappReportNumber: "വാട്ട്സ്ആപ്പ് റിപ്പോർട്ട് നമ്പർ",
    businessTimezone: "ബിസിനസ് ടൈംസോൺ",
    liveRefresh: "തൽസമയ റിഫ്രഷ്",
    keepTotalsUpToDate: "ആകെ തുകകൾ പുതുക്കി വെക്കുക",
    previousBusinessData: "പഴയ ബിസിനസ് വിവരങ്ങൾ",
    nextOffer: "അടുത്തത്: ഓഫർ",
    commissionProgress: "കമ്മീഷൻ പുരോഗതി",
    persistentCommissionProgress: "തുടർച്ചയായ കമ്മീഷൻ പുരോഗതി",
    filteredOffersEarned: "ലഭിച്ച ഓഫറുകൾ (ഫിൽറ്റർ ചെയ്തത്)",
    offerRecords: "ഓഫർ രേഖകൾ",
    nextStockPickup: "അടുത്തത്: സ്റ്റോക്ക് എടുക്കൽ",
    nextSales: "അടുത്തത്: വിൽപ്പന",
    nextReview: "അടുത്തത്: പരിശോധന",
    alQuwwa: "AL QUWWA",
    previousBusinessDate: "പഴയ ബിസിനസ് തീയതി",
    viewPreviousDayCaps: "മുൻപത്തെ ദിവസം കാണുക",
    closePreviousDayCaps: "മുൻപത്തെ ദിവസം അടയ്ക്കുക",
    started: "ആരംഭിച്ചു",
    reopened: "വീണ്ടും തുറന്നു",
    businessDate: "ബിസിനസ് തീയതി",
    pickupReason: "എടുത്തതിന്റെ കാരണം",
  },
  pagination: {
    showing: "കാണിക്കുന്നത്",
    of: "ൽ",
    records: "രേഖകൾ",
    rows: "വരികൾ",
    page: "പേജ്",
  },
  offers: {
    earned: "ഓഫർ ലഭിച്ചു",
    received: "ഓഫർ സ്വീകരിച്ചു",
    giftNumber: "ഗിഫ്റ്റ് നമ്പർ",
    earnedAt: "ലഭിച്ച തീയതിയും സമയവും",
    receivedAt: "സ്വീകരിച്ച തീയതിയും സമയവും",
    cycle: "സൈക്കിൾ",
  },
  messages: {
    timeNotSynchronized: "സമയം സിൻക്രോണൈസ് ചെയ്തിട്ടില്ല",
    serverTimeSynchronized: "സെർവർ സമയം സിൻക്രോണൈസ് ചെയ്തു",
    closePreviousDayWarning: "പുതിയ ബിസിനസ് ദിവസം ആരംഭിക്കുന്നതിന് മുൻപ് കഴിഞ്ഞ ബിസിനസ് ദിവസം അടയ്ക്കുക.",
    sessionEarningsTitle: "സെഷൻ വരുമാനം",
    noProductsAvailable: "ലഭ്യമായ ഉൽപ്പന്നങ്ങളൊന്നുമില്ല.",
    loading: "ലഭ്യമാക്കുന്നു...",
    errorTitle: "ട്രാക്കർ തുറക്കാൻ കഴിഞ്ഞില്ല",
    deductedFromCompanyPayable: "കമ്പനിക്ക് നൽകേണ്ട തുകയിൽ നിന്ന് കുറയ്ക്കും (കമ്മീഷൻ കുറയ്ക്കില്ല)",
    noOtherExpenses: "ഇന്ന് മറ്റ് ചെലവുകൾ രേഖപ്പെടുത്തിയിട്ടില്ല.",
    noBusinessDayStarted: "ഇന്ന് ബിസിനസ് ദിവസം ആരംഭിച്ചിട്ടില്ല.",
    calendarDateChanged: "ക്യാലണ്ടർ തീയതി മാറിയിരിക്കുന്നു",
    whatWouldYouLikeToDo: "നിങ്ങൾക്ക് എന്താണ് ചെയ്യേണ്ടത്?",
    chooseActionToGetStarted: "തുടങ്ങുന്നതിനായി ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക.",
    endOfDay: "ദിവസാവസാനം",
    reviewTotalsBeforeClosing: "അടയ്ക്കുന്നതിന് മുൻപ് ആകെ തുകകൾ പരിശോധിക്കുക.",
    selectTodaysPickedQuantities: "ഇന്ന് എടുത്ത എണ്ണം തിരഞ്ഞെടുക്കുക",
    productsLeftAt0NotPicked: "0 ആയി കിടക്കുന്ന ഉൽപ്പന്നങ്ങൾ ഇന്ന് എടുത്തിട്ടില്ല.",
    confirmAndStartDay: "ദിവസം ആരംഭിക്കുന്നത് സ്ഥിരീകരിക്കണോ?",
    newBusinessDayCreatedAfterConfirmation: "സ്ഥിരീകരിച്ചതിന് ശേഷം മാത്രമേ പുതിയ ബിസിനസ് ദിവസം സൃഷ്ടിക്കപ്പെടുകയുള്ളൂ. മുൻപത്തെ എണ്ണവും ബാക്കിയുള്ള സ്റ്റോക്കും പുതിയതിലേക്ക് മാറില്ല.",
    allProductsStartAtZero: "എല്ലാ ഉൽപ്പന്നങ്ങളും പൂജ്യത്തിൽ നിന്ന് തുടങ്ങും.",
    originalPickupUnchanged: "തുടക്കത്തിൽ എടുത്ത എണ്ണം മാറില്ല. പുതിയ എണ്ണം മാത്രം ചേർക്കുക.",
    reviewNewQuantitiesBeforeSaving: "സേവ് ചെയ്യുന്നതിന് മുൻപ് പുതിയ എണ്ണം പരിശോധിക്കുക.",
    dayStartAndCloseNeverReset: "ദിവസം തുടങ്ങുന്നതും അടയ്ക്കുന്നതും ഈ സൈക്കിളുകളെ റീസെറ്റ് ചെയ്യില്ല.",
    tapEarnedOfferToMarkReceived: "ലഭിച്ച (EARNED) ഓഫർ സ്വീകരിച്ചതായി രേഖപ്പെടുത്താൻ അതിൽ ക്ലിക്ക് ചെയ്യുക.",
    tapToMarkReceived: "സ്വീകരിച്ചതായി രേഖപ്പെടുത്താൻ ക്ലിക്ക് ചെയ്യുക",
    markOfferAsReceived: "ഈ ഓഫർ സ്വീകരിച്ചതായി രേഖപ്പെടുത്തണോ?",
    confirmActuallyReceivedOffer: "ഈ ഓഫർ യഥാർത്ഥത്തിൽ ലഭിച്ചുവെന്ന് സ്ഥിരീകരിക്കുക. ഇത് ഓഫറിന്റെ സ്റ്റാറ്റസ് EARNED എന്നതിൽ നിന്ന് RECEIVED എന്നാക്കി മാറ്റും.",
    undoReceivedStatus: "സ്വീകരിച്ച സ്റ്റാറ്റസ് മാറ്റണോ?",
    changeOfferBackToEarned: "ഇത് ഓഫർ RECEIVED എന്നതിൽ നിന്ന് തിരികെ EARNED എന്നാക്കി മാറ്റും.",
    reviewPreviousDayBeforeClosing: "മുൻപത്തെ ദിവസത്തെ സ്റ്റോക്കും കണക്കുകളും അടയ്ക്കുന്നതിന് മുൻപ് പരിശോധിക്കുക. അടച്ചുകഴിഞ്ഞാൽ വീണ്ടും തുറക്കാതെ പുതിയ വിൽപ്പനകൾ ചേർക്കാൻ കഴിയില്ല.",
    tapToViewFullClosureSummary: "പൂർണ്ണ വിവരങ്ങൾ കാണാൻ ക്ലിക്ക് ചെയ്യുക",
    copyMessage: "മെസ്സേജ് പകർത്തുക",
    expensesCanOnlyBeAddedToActive: "സജീവമായ ബിസിനസ് ദിവസത്തിൽ മാത്രമേ ചെലവുകൾ ചേർക്കാനാകൂ. ചെലവുകൾ രേഖപ്പെടുത്താൻ ഒരു ദിവസം ആരംഭിക്കുക.",
    reopenCurrentBusinessDay: "ഇന്നത്തെ ബിസിനസ് ദിവസം വീണ്ടും തുറക്കണോ?",
    businessDayAlreadyClosedReopen: "ഈ ബിസിനസ് ദിവസം ഇതിനകം അടച്ചതാണ്. വീണ്ടും തുറന്നാൽ കൂടുതൽ ഉൽപ്പന്നങ്ങൾ എടുക്കാനും പുതിയ വിൽപ്പനകൾ നടത്താനും കഴിയും. നിലവിലുള്ള വിവരങ്ങൾ മാറില്ല; കഴിഞ്ഞ റിപ്പോർട്ടുകൾ കാലഹരണപ്പെടും.",
    resetCurrentBusinessDay: "ഇന്നത്തെ ബിസിനസ് ദിവസം റീസെറ്റ് ചെയ്യണോ?",
    sureYouWantToWipeBusinessDay: "ഇന്നത്തെ ബിസിനസ് ദിവസം പൂർണ്ണമായും മായ്ച്ചു കളയണോ? ഇത് ഇന്നത്തെ സെഷനും സ്റ്റോക്ക് ട്രാക്കിംഗും പൂർണ്ണമായും ഡിലീറ്റ് ചെയ്യും.",
    cancelHistoricalDraft: "പഴയ വിവരങ്ങളുടെ ഡ്രാഫ്റ്റ് റദ്ദാക്കണോ?",
    allUnsavedDraftDataDiscarded: "സേവ് ചെയ്യാത്ത വിവരങ്ങൾ നഷ്ടപ്പെടും. ഡാറ്റാബേസിൽ സേവ് ചെയ്ത പഴയ രേഖകളെ ഇത് ബാധിക്കില്ല.",
    newDayUnavailable: "പുതിയ ദിവസം ലഭ്യമല്ല",
    additionalPickupUnavailable: "കൂടുതൽ എടുക്കാൻ ലഭ്യമല്ല",
    reopenTrustedBusinessDayFirst: "ആദ്യം നിലവിലെ ബിസിനസ് ദിവസം വീണ്ടും തുറക്കുക.",
    chooseAProduct: "ഒരു ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക",
    dailyStock: "പ്രതിദിന സ്റ്റോക്ക്",
    stockResetsOnlyWhenNewDayStarted: "പുതിയ ദിവസം ആരംഭിക്കുമ്പോൾ മാത്രമേ സ്റ്റോക്ക് റീസെറ്റ് ആവുകയുള്ളൂ.",
    recordPetrolFoodAndOtherCosts: "പെട്രോൾ, ഭക്ഷണം, മറ്റ് ചിലവുകൾ രേഖപ്പെടുത്തുക",
    originalStart: "യഥാർത്ഥ ആരംഭം",
    originalClose: "യഥാർത്ഥ അവസാനം",
    totalPicked: "ആകെ എടുത്തത്",
    totalSold: "ആകെ വിറ്റത്",
    totalRemaining: "ആകെ ബാക്കി",
    mandatoryReopenReason: "തുറക്കാനുള്ള കാരണം",
    resetActiveBusinessDayQ: "ഇന്നത്തെ ബിസിനസ് ദിവസം റീസെറ്റ് ചെയ്യണോ?",
    customerReturned: "ഉപഭോക്താവ് തിരികെ നൽകി",
    returnSuccess: "വിൽപ്പന വിജയകരമായി തിരികെ എടുത്തു",
    pickupCorrectionSuccess: "പിക്കപ്പ് വിജയകരമായി തിരുത്തി",
    defaultCorrectionReason: "അബദ്ധത്തിൽ തെറ്റായ എണ്ണം രേഖപ്പെടുത്തി",
  }
};
